CREATE SEQUENCE  "BANK"."SEQUENCE_LOGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

create or replace PROCEDURE INSERT_LOG (vINFO IN VARCHAR2) AS 
    nUSER LOGS.V_USER%TYPE;
BEGIN
    SELECT USER INTO nUSER FROM DUAL;
    INSERT INTO LOGS(N_LOG, V_USER, D_DATE, V_INFO) VALUES (DEFAULT, nUSER, DEFAULT, vINFO);
END;
