create or replace PROCEDURE INSERT_SUB_TITULARES (nCLIENTE IN NUMBER, vIBAN IN NVARCHAR2) AS 
vEXCEPTION EXCEPTION;
BEGIN   
    INSERT INTO SUB_TITULARES(N_CLIENTE, V_IBAN) VALUES (nCLIENTE, vIBAN);

EXCEPTION
    WHEN vEXCEPTION THEN
         INSERT_LOG('ERRO AO EXECUTAR PROCEDIMENTO INSERT_SUB_TITULARES');
END INSERT_SUB_TITULARES;